### ISSUE TITLE
Background center

### ISSUE THREAD

**Issue by binarymonkey84** [vb/lazyframe#13]
Could you add `background-position: center` to the CSS (`.lazyframe`) for the cover image? Otherwise the cover image doesn't look great in some situations, like with the following code:

`<div class="lazyframe" data-src="https://www.youtube.com/embed/3n35a28WL4s" data-vendor="youtube"></div>`

**Results in this:**

![image](https://user-images.githubusercontent.com/20354825/38416532-e8e46f54-398c-11e8-9c53-0fb96d1460c7.png)

**With `background-position: center` applied, it looks correct as below:**
![image](https://user-images.githubusercontent.com/20354825/38416603-1efdd224-398d-11e8-811a-c9e85bdfdf29.png)

Matt

**Comment by viktorbergehall** [comment]
Hi Matt,
That seems like a legit suggestion. Would you like to submit a pull request?

**Comment by niftylettuce** [comment]
PR welcome
