### ISSUE TITLE
Problem with slick carousel initialization

### ISSUE THREAD

**Issue by Johnczek** [vb/lazyframe#16]
Hello, 

I have a small problem with lazy loader and slick carousel initialization. I want to put 0..N videos inside slick like this
![image](https://user-images.githubusercontent.com/22480816/40618584-3a4cb7a6-6292-11e8-8681-842ee2490b25.png)

Problem is obvious. SOmetimes happen that some semi-visible parts are "red backgrounded". Is there any way how to get rid of that and load thumbnails for semi-visible videos? (Or load and paste thumbnails for all lazyloaded videos?)

Thank you for your time.

**Comment by niftylettuce** [comment]
PR welcome
