### ISSUE TITLE
Ratio issues with Vimeo videos on large widths

### ISSUE THREAD

**Issue by sfusato** [vb/lazyframe#24]
Steps to reproduce the issue on the [demo](https://vb.github.io/lazyframe/) page:

1. Change the `max-width` to `1000px` for the `container`
```
.container {
    max-width: 1000px;
    margin: 0 auto;
    width: 100%;
}
```
2. Play a Vimeo video

The video won't occupy the full-space of the thumbnail image (see my screenshot):
![lazyframe_vimeo](https://user-images.githubusercontent.com/19363153/50599857-e8db4900-0eb7-11e9-9c85-678e683ab691.png)

This doesn't seem to affect Youtube's videos though.

**Comment by sporkman** [comment]
I'm actually seeing something similar in smaller videos. The ratio of the video and the video thumbnail are off, but in my case, I have extra space on the top and bottom of the video and the thumbnail shows through there.

screenshot (yes, these are very tiny videos!):

<img width="414" alt="Screen Shot 2020-01-10 at 1 00 59 AM" src="https://user-images.githubusercontent.com/510750/72129689-271a0c80-3345-11ea-8422-c9d32089ef60.png">

**Comment by smeedijzer-internet** [comment]
Same here

**Comment by Joel-James** [comment]
Same for me too.

**Comment by niftylettuce** [comment]
PR welcome
