### ISSUE TITLE
Chrome autoplay

### ISSUE THREAD

**Issue by Callan05** [vb/lazyframe#26]
Hey,
I love this little script, so simple but great for my visitors.

I've noticed that my videos are no longer autoplaying when clicked.
I think this is only in Chrome and related to their new autoplay policies.

are you able to add
 allow='autoplay' to the iframe?
IE:
<iframe src="https://www.youtube.com/embed/A-t5B4pZdYc/?autoplay=1" frameborder="0" allowfullscreen=""  allow='autoplay' ></iframe>

i think this can be done by adding:
n.setAttribute("allow","autoplay"),
directly after
n.setAttribute("allowfullscreen",""),

but I'm not sure if that has other impacts.
It did work for me in my limited testing though.

thanks!

**Comment by way2naman** [comment]
Hi i tried the code but it is still not working in mobile, can you please help

**Comment by mingdazhang2** [comment]
add ',n.setAttribute("allow","autoplay;encrypted-media")' after n.setAttribute("src",e.src),n.setAttribute("frameborder",0),n.setAttribute("allowfullscreen","")

that works for me. 
Another question, how can I set a default 'sddefault.jpg' image for youtube video

**Comment by mitchellcarroll** [comment]
@way2naman HTML5 autoplay is unfortunately disabled for android and iOS. 
https://developers.google.com/web/updates/2017/09/autoplay-policy-changes
https://webkit.org/blog/7734/auto-play-policy-changes-for-macos

@mingdazhang2 code works for autoplaying for laptop/desktop devices.

**Comment by sporkman** [comment]
Just confirming that @mingdazhang2's fix still works great for chrome. For iOS, it would be nice if we appended "muted=1" if we're on mobile, that would solve the "click twice to play" annoyance.

**Comment by niftylettuce** [comment]
PR welcome
