### ISSUE TITLE
Add class when iframe is loaded

### ISSUE THREAD

**Issue by sporkman** [vb/lazyframe#32]
In my use of lazyframe, I found that I needed to make some css changes when the iframe loads. Mainly just want to ensure that my own background pops into place, the play button is hidden if an odd aspect-ratio video loads, etc.

In the unminified lazyframe.js, I did this, which seems to work:

```
        function n(e) {
            var t = this;
            if (e instanceof HTMLElement != !1 && !e.classList.contains("lazyframe--loaded")) {
                var n = {
                    el: e,
                    settings: i(e)
                };
                n.el.addEventListener("click", function() {
                    n.el.appendChild(n.iframe);
                    n.el.classList.add("lazyframe--frame-loaded");
                    var i = e.querySelectorAll("iframe");
                    n.settings.onAppend.call(t, i[0])
                }), d.lazyload ? l(n) : u(n, !!n.settings.thumbnail)
            }
        }
```
(if it's not clear, the single line change is `n.el.classList.add("lazyframe--frame-loaded");`
I guess two questions:

- Is this correct-ish?
- Could this, or a more appropriate option, be made a feature?

**Comment by niftylettuce** [comment]
PR welcome

**Comment by sporkman** [comment]
I'm sorry, does this mean I should open a new problem report or that this is rejected?
