### ISSUE TITLE
bug: player requires double click to launch the video

### ISSUE THREAD

**Issue by pahan35** [vb/lazyframe#37]
Hello there.

We tried to use this plugin to lazyload a youtube video.

When we tried to use it, we noticed that it requires to do 2 clicks most of the time to launch the video. This is reproducible even with the provided demo. [Screencast](https://recordit.co/9Vv37bRmSX)

However, we noticed that there https://github.com/paulirish/lite-youtube-embed is a plugin, where it works without a double click.

We debugged the current plugin and figured out that to solve the double click problem we need to do 2 things.
1. Add prefetch logic, which is here https://github.com/paulirish/lite-youtube-embed/blob/master/src/lite-yt-embed.js#L87-L99 in that plugin.
2. Add allow iframe attribute with at least 'autoplay' value, which is here https://github.com/paulirish/lite-youtube-embed/blob/master/src/lite-yt-embed.js#L111.

PR welcomed to solve this issue.

**Comment by laozhou42** [comment]
I added a autoplay feature in this [pr](https://github.com/vb/lazyframe/pull/39). hope can fix you problem.
