### ISSUE TITLE
Vimeo videos no longer return correct image

### ISSUE THREAD

**Issue by maciejdudzinski** [vb/lazyframe#48]
See vimeo example here: https://vb.github.io/lazyframe/
![Screenshot from 2021-09-21 15-39-30](https://user-images.githubusercontent.com/35724931/134181213-3074c4cf-3baf-41c2-9a22-86aa2db22c6c.png)

//edit
I see that it happens with videos that return "Video is not rated. Log in to watch." when opened. 
Other videos still work.

**Comment by vb** [comment]
Thanks for the report.
This seems to be an issue with the noembed service. There is a ticket on this here https://github.com/leedo/noembed/issues/120
