### ISSUE TITLE
Need to tap twice to play YouTube video on touchscreens

### ISSUE THREAD

**Issue by Bossieh** [vb/lazyframe#55]
First of all thanks for this awesome library!

It seems that I need to tap twice to play a YouTube video, you can test it on the demo-page: https://vb.github.io/lazyframe/

Is this intended behavior?

**Comment by vb** [comment]
Thank you for the feedback!
I'm afraid it is no longer possible to autoplay Youtube videos on mobile devices. 
https://developers.google.com/youtube/iframe_api_reference#Mobile_considerations
