### ISSUE TITLE
2.3.1 and 2.2.7 versions isn't working after update

### ISSUE THREAD

**Issue by Sogl** [vb/lazyframe#57]
Previously I was on `2.2.4`. 

What I see in `node_modules` now:
![image](https://user-images.githubusercontent.com/7556290/161384998-da2db0a9-d4bd-4dce-bf59-84f94c77f109.png)
No `src` folder, no scss files.

My js code:
```js

$(document).ready(function() {
    //YouTube lazy load
    let elements = $('.lazyframe');
    lazyframe(elements, {
        apikey: 'my-api-key,
    });

});
```

No changes in code except loading css with `@import '~lazyframe/dist/lazyframe.css';`, but now all YT videos isn't working:
![image](https://user-images.githubusercontent.com/7556290/161385318-8843926e-ea96-4d7c-a62b-66e53b5d955d.png)

Videos don't play, clicks don't work.

What is it?

**Comment by vb** [comment]
Hi @Sogl, thanks for opening an issue.
That's weird. When I'm installing 2.2.7 I get the src directory. 
- Could you supply a bit more info on how you are working with the package?
- Is 2.2.4 still working for you?

**Comment by Sogl** [comment]
>Could you supply a bit more info on how you are working with the package?

I wrote above how I work with the library, this code I use in html:
```html
<div class="col-lg-6 col-md-12 pt-5 pt-lg-0 review">
    <div class="embed-responsive embed-responsive-16by9">
        <div class="embed-responsive-item lazyframe" data-src="https://www.youtube.com/embed/mYvIdEo" 
data-vendor="youtube"></div>
    </div>
    <div class="embed-text pt-3">Some text</div>
</div>
```

>Is 2.2.4 still working for you?

Yes.

I tried 2.2.7 one more time with command `yarn add lazyframe@2.2.7` and now it works. So my issue is about v 2.3.1 only.

**Comment by vb** [comment]
2.3.1 is still in beta and I will look at it when I get the chance. Thanks for reporting
